// Copyright Akira Miyakoda 2022.
// Distributed under the Boost Software License, Version 1.0.
// See accompanying file LICENSE
// or copy at http://www.boost.org/LICENSE_1_0.txt

#include "tables/singlebyte/hashtable.h"
#include "tables/singlebyte/ibm866.h"
#include "tables/singlebyte/iso_8859_10.h"
#include "tables/singlebyte/iso_8859_13.h"
#include "tables/singlebyte/iso_8859_14.h"
#include "tables/singlebyte/iso_8859_15.h"
#include "tables/singlebyte/iso_8859_16.h"
#include "tables/singlebyte/iso_8859_2.h"
#include "tables/singlebyte/iso_8859_3.h"
#include "tables/singlebyte/iso_8859_4.h"
#include "tables/singlebyte/iso_8859_5.h"
#include "tables/singlebyte/iso_8859_6.h"
#include "tables/singlebyte/iso_8859_7.h"
#include "tables/singlebyte/iso_8859_8.h"
#include "tables/singlebyte/koi8_r.h"
#include "tables/singlebyte/koi8_u.h"
#include "tables/singlebyte/macintosh.h"
#include "tables/singlebyte/windows_1250.h"
#include "tables/singlebyte/windows_1251.h"
#include "tables/singlebyte/windows_1252.h"
#include "tables/singlebyte/windows_1253.h"
#include "tables/singlebyte/windows_1254.h"
#include "tables/singlebyte/windows_1255.h"
#include "tables/singlebyte/windows_1256.h"
#include "tables/singlebyte/windows_1257.h"
#include "tables/singlebyte/windows_1258.h"
#include "tables/singlebyte/windows_874.h"
#include "tables/singlebyte/x_mac_cyrillic.h"
